export default {
    THEME_CHANGE:'THEME_CHANGE',
    THEME:'THEME_INIT',
    POPULAR_REFRESH:'POPULAR_REFRESH',
    POPULAR_REFRESH_FAIL:'LOAD_REFRESH_FAIL',
    POPULAR_REFRESH_SUCCESS:'LOAD_REFRESH_SUCCESS',
    POPULAR_LOAD_MPRE_SUCCESS:'POPULAR_LOAD_MPRE_SUCCESS',
    POPULAR_LOAD_MPRE_FALL:'POPULAR_LOAD_MPRE_FALL'
}