export default {
    THEME_CHANGE:'THEME_CHANGE',
    THEME:'THEME_INIT',
    POPULAR_REFRESH:'POPULAR_REFRESH',
    LOAD_POPULAR_FAIL:'LOAD_POPULAR_FAIL',
    LOAD_POPULLAR_SUCCESS:'LOAD_POPULLAR_SUCCESS'
}